(() => {
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const portraits={ranger:'aeldari-ranger',sororitas:'sororitas','space-marine':'space-marine',human:'rogue-trader','rogue-trader':'rogue-trader',drukhari:'drukhari-wych'};
  function traits(hero){
    const inventory=window.Supplies?.inventory;
    const unit=inventory?.run?.party.find(u=>u.id===hero.id)||{...hero,...inventory?.state.heroProfiles?.[hero.id]};
    const negative=window.Morale.entries(unit),positive=window.Morale.entries(unit,true);
    const badge=(list,good)=>{if(!list.length)return '';const label=(good?'Positive traits: ':'Negative traits: ')+list.map(t=>t.name).join(', ');return `<span class="portrait-trait ${good?'positive':'negative'}" title="${escape(label)}" role="img" aria-label="${escape(label)}"><svg viewBox="0 0 32 38" aria-hidden="true">${good?'<path class="trait-arrow" d="M7 37h18V15h6L16 1 1 15h6z"/><path class="trait-symbol" d="m16 8 2.5 8 7.5 2.5-7.5 2.5-2.5 8-2.5-8L6 18.5l7.5-2.5z"/>':'<path class="trait-arrow" d="M7 1h18v22h6L16 37 1 23h6z"/><path class="trait-symbol" d="M7 12a9 9 0 0 1 18 0v6l-4 3v5H11v-5l-4-3z"/><path fill="#b3a17a" d="M10 11h5v5h-5zm8 0h5v5h-5zm-2 5 3 5h-6z"/>'}</svg><b>${list.length}</b></span>`;};
    return `<span class="portrait-traits">${badge(positive,true)}${badge(negative,false)}</span>`;
  }
  function face(hero){const file=portraits[hero.classId||hero.id]||'aeldari-ranger';return `<span class="crew-face face-${file}" role="img" aria-label="${escape(hero.name)} portrait" style="background-image:url('portraits/${file}.png')">${traits(hero)}</span>`;}
  function bar(label,value,max,kind){const n=Math.max(0,Math.min(max,Number(value)||0));return `<div class="crew-stat ${kind}"><span>${label}</span><div class="crew-bar" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${n}"><i style="width:${n/max*100}%"></i><b>${n} / ${max}</b></div></div>`;}
  function party(crew){crew=[...crew].sort((a,b)=>b.rank-a.rank);return `<div class="expedition-party" aria-label="Expedition crew">${Array.from({length:4},(_,i)=>{const u=crew[i];if(u)window.Morale.normalize(u);return u?`<article class="crew-card ${u.hp<=0?'fallen':''}" role="button" tabindex="0" data-action="inspect-hero-${escape(u.id)}" aria-label="Inspect ${escape(u.name)}" data-crew-hud="${escape(u.id)}">${face(u)}<div class="crew-card-info">${bar('HP',u.hp,u.maxHp||28,'health')}${bar('Morale',u.morale??100,u.maxMorale||100,'morale')}</div></article>`:`<div class="crew-card crew-vacant" aria-label="Empty party slot ${i+1}"><span>＋</span></div>`;}).join('')}</div>`;}
  function needs(run,rations){
    const energy=Math.max(0,Math.min(100,Math.ceil(Number(run?.energy)||0))),hunger=Math.max(0,Math.min(100,Math.floor(Number(run?.hunger)||0))),demand=window.Supplies?.inventory?.foodDemand?.()||0;
    const meter=(label,value,kind,detail)=>`<div class="party-need ${kind}"><header><strong>${label}</strong><span>${detail}</span></header><div class="party-need-track" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${value}"><i style="width:${value}%"></i></div></div>`;
    return `<div class="party-needs" aria-label="Party supplies">${meter('ENERGY',energy,'energy',`${energy} / 100`)}${meter('HUNGER',hunger,'hunger',hunger>=100?`MEAL DUE · ${demand} RATIONS`:`${hunger}% · ${rations} RATIONS`)}</div>`;
  }
  function hub(inventory,heroes){return `<aside class="hub-commander hub-roster" aria-label="Crew"><header class="hub-roster-header"><span>ACTIVE MANIFEST</span><strong>Expedition crew</strong></header>${(Array.isArray(heroes)?heroes:[heroes]).map((hero,index)=>`<div class="hub-roster-member faction-${escape(hero.classId||hero.id)}" role="button" tabindex="0" data-crew-hud="${escape(hero.id)}" data-action="inspect-hero-${escape(hero.id)}" aria-label="Inspect ${escape(hero.name)}"><i class="hub-roster-index">${String(index+1).padStart(2,'0')}</i>${face(hero)}<div><strong>${escape(hero.name)}</strong><span>RANK ${hero.level||1}${inventory.resting(hero.id)?' · RESTING':''}</span></div><i class="hub-roster-rune" aria-hidden="true"></i></div>`).join('')}<footer>ROGUE TRADER AUXILIA</footer></aside>`;}
  window.GameHUD={face,party,needs,hub,traits};
})();
